## 브로드캐스트
넘파이는 브로드캐스트라는 기능을 제공하여 형상이 다른 배열끼리의 연산을 수행할 수 있습니다.

In [2]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(A*10)

[[10 20]
 [30 40]]


In [ ]:
import numpy as np
A = np.array([1,2],[3,4])
B = np.array([10,20])
print(A*B)

벡터의 내적과 행렬의 곱
x * y = x1y1 + x2y2 + x3y3 +....+ xnyn
x = (x1, .... , xn)
y = (y1, .... , yn)
벡터의 내적은 두 벡터에서 대응하는 원소들의 곱을 모두 더한 것입니다.
벡터의 내적은 직관적으로 '두 벡터가 얼마나 같은 방향을 있는가'를 나타냅니다.
벡터의 길이가 1인 경우로 한정하면, 완전히 같은 방향을 두 벡터의 내적은 1이 됩니다.
받내로, 반대 방향을 향하는 두 벡터의 내적은 -1입니다.

In [2]:
# 백터의 내적
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


In [3]:
# 행렬으 곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.matmul(A,B))

[[19 22]
 [43 50]]


벡터의 내적과 행렬의 곱 모두에 np.dot()을 사용할 수 있습니다. np.dot(x,y)의 인수가 모두 1차원 배열이면 벡터의 내적을 계산하고, 2차원 배열이면 행렬의 곱을 계산합니다.
다만, 가능하면 구분하여 코드의 노리와 의도를 명확히 해주는 게 좋습니다.

#### numpy.random.randn(do, d1, ..., dn)
- Return a sample (or samples) from the "standard normal" distribution(표준분포로부터 sample을 반환한다).
- 파라메터 d는 차원을 의미하며 d0은 일차원 d1은 이차원... dn은 (n-1) 차원을 나타낸다. 
- d0을 1로 할 경우 1차원에서 하나의 랜덤수를 반환하며 2일경우 두개 의 랜덤수를 반환합니다.

In [5]:
print(np.random.randn(1))
print(np.random.randn(2))
print(np.random.randn(2,3))

[0.40185176]
[ 1.88051846 -0.01262259]
[[ 0.34059703  0.32225623 -0.02431969]
 [-0.64695192  0.18210189 -0.54517972]]


#### numpy.argmax(a, axis=None, out=None)
- Returns the indices of the maximum values along an axis(axis에 따라 maximum values의 색인을 반환한다).

In [9]:
a = np.arange(6).reshape(2,3) + 10
print(a)
print(np.argmax(a)) # 가장 큰 index 반환
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

[[10 11 12]
 [13 14 15]]
5
[1 1 1]
[2 2]


#### numpy.random.choice(a, size=None, replace=True, p=None)
- Generates a random sample from a given 1-D array(1차원 array a에서 무작위로 하나를 반환한다).
- p는 a의 각 entry의 확률로 확률이 높은 entry가 반환률이 높다.
- p를 None할 경우 a의 entry확률은 uniform distribution하게 할당된다.

In [66]:
print(np.random.choice(10)) # 10 미만으로 무작위 하나 반화
print(np.random.choice(4,10)) # 4미만으로 10개 반환

8
[0 0 1 1 3 3 0 3 0 3]


##### np.random.randint(low, high=None, size=None, dtype='')
- Return random integers from low (inclusive) to high (exclusive)(low는 이상의 개념으로 포함되고 high는 미만의 개념이므로 포함되지 않는다).

In [79]:
print(np.random.randint(0, 10))

1
