In [2]:
import numpy as np
import pandas as pd

## Dataframe란
DataFrame은 2차원 자료구조인 DataFrame는 행과 열이 있는 테이블 데이타(Tabular Data)를 받아들이는데, 아래 예제는 그 한가지 방법으로서 열(column)을 dict의 Key로, 행(row)을 dict의 Value로 한 Dictionary 데이타를 pd.DataFrame()을 사용하여 pandas의 Data Frame 자료구조로 변환한 예이다.

### Dataframe 생성 방법

In [3]:
data = {
    'year':[2016, 2017, 2018],
    'GDP rate':[2.8, 3.1,3.0],
    'GDP':['1.637M','1.73M','1.83M']
}
df = pd.DataFrame(data)
df

year  GDP rate     GDP
0  2016       2.8  1.637M
1  2017       3.1   1.73M
2  2018       3.0   1.83M

In [4]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [9]:
daeshin = {'open':  [11650, 11100, 11200, 11100, 11000],
           'high':  [12100, 11800, 11200, 11100, 11150],
           'low' :  [11600, 11050, 10900, 10950, 10900],
           'close': [11900, 11600, 11000, 11100, 11050]}
date = ['16.02.29', '16.02.26', '16.02.25', '16.02.24', '16.02.23']
daeshin_day = pd.DataFrame(daeshin, columns=['open', 'high', 'low', 'close'], index=date)
daeshin_day

open   high    low  close
16.02.29  11650  12100  11600  11900
16.02.26  11100  11800  11050  11600
16.02.25  11200  11200  10900  11000
16.02.24  11100  11100  10950  11100
16.02.23  11000  11150  10900  11050

#### Numpy to Pandas Dataframe

In [14]:
# Set the seed for a reproducible sample
np.random.seed(0)  
df = pd.DataFrame(np.random.randn(5, 3), columns=['A', 'B', 'C'])

df

A         B         C
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
2  0.950088 -0.151357 -0.103219
3  0.410599  0.144044  1.454274
4  0.761038  0.121675  0.443863

## Dataframe method

In [35]:
np.random.seed(0)  
df = pd.DataFrame(np.random.randn(5, 3), columns=['A', 'B', 'C'])

print(df.info())
print(df.ndim) # Returns dimension of dataframe
print(df.shape)
print(df.size)
print(len(df))
print(df.columns)
print(df.values)
print(df.head)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
dtypes: float64(3)
memory usage: 248.0 bytes
None
2
(5, 3)
15
5
Index(['A', 'B', 'C'], dtype='object')
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]]
<bound method NDFrame.head of           A         B         C
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
2  0.950088 -0.151357 -0.103219
3  0.410599  0.144044  1.454274
4  0.761038  0.121675  0.443863>


## DataFrame의 행(row) 선택하기(filtering)

In [12]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), columns=['num1', 'num2'])
df[df.num1>3][['num1', 'num2']]

num1  num2
1     4     6
2     5     4
3     8     0
4     6     5
9     7     3

### loc and iloc
- iloc: 행번호(row number)로 선택하는 방법
- loc: label이나 조건표현으로 선택하는 방법

In [38]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), columns=['num1', 'num2'])
df

num1  num2
0     2     3
1     8     1
2     3     3
3     3     7
4     0     1
5     9     9
6     0     4
7     7     3
8     2     7
9     2     0

In [39]:
print(df.iloc[1]) # 두번째 행만
print(df.iloc[-1]) # 마지막 행만
# Columns:
print(df.iloc[:,0]) # 첫번째 열만
print(df.iloc[:,1]) # 두번째 열만
print(df.iloc[:,-1]) # 마지막 열만

num1    8
num2    1
Name: 1, dtype: int32
num1    2
num2    0
Name: 9, dtype: int32
0    2
1    8
2    3
3    3
4    0
5    9
6    0
7    7
8    2
9    2
Name: num1, dtype: int32
0    3
1    1
2    3
3    7
4    1
5    9
6    4
7    3
8    7
9    0
Name: num2, dtype: int32
0    3
1    1
2    3
3    7
4    1
5    9
6    4
7    3
8    7
9    0
Name: num2, dtype: int32


### loc and iloc 조건 검색

In [48]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), 
                  columns=['num1', 'num2'], 
                  index=['idx0', 'idx1', 'idx2', 'idx3', 'idx4', 'idx5', 'idx6', 'idx7', 'idx8', 'idx9'])

df

num1  num2
idx0     0     3
idx1     5     9
idx2     4     4
idx3     6     4
idx4     4     3
idx5     4     4
idx6     8     4
idx7     3     7
idx8     5     5
idx9     0     1

In [57]:
print(df.loc['idx0'])
print(df.iloc[0])

num1    0
num2    3
Name: idx0, dtype: int32
num1    0
num2    3
Name: idx0, dtype: int32


In [56]:
print(df.loc[['idx0', 'idx2']])
print(df.iloc[[0, 2]])

      num1  num2
idx0     0     3
idx2     4     4
      num1  num2
idx0     0     3
idx2     4     4


In [60]:
print(df.loc[['idx0', 'idx2'], ['num1']])
print(df.iloc[[0, 2], [0]])

      num1
idx0     0
idx2     4
      num1
idx0     0
idx2     4


In [66]:
print(df.loc[df['num1'] == 4])
print(df.loc[df['num1'] == 4, ['num1']])

      num1  num2
idx2     4     4
idx4     4     3
idx5     4     4
      num1
idx2     4
idx4     4
idx5     4


## 반복문
DataFrame 객체의loc(),iloc(),iterrows(),itertuples(),iteritems()및apply()메소드를 사용하여 DataFrame Pandas 행을 반복 할 수도 있음  
count()는 Null 값이 아닌 행(count Non-null rows)만 세며,  
size() 는 Null 값인 행도 모두 포함해서 행(size of all rows)을 센다  


https://www.delftstack.com/ko/howto/python-pandas/how-to-iterate-through-rows-of-a-dataframe-in-pandas/

### iterrows()

In [68]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), columns=['num1', 'num2'])

for index, row in df.iterrows():
    print("%d %s" % (index, row))

0 num1    2
num2    9
Name: 0, dtype: int32
1 num1    2
num2    3
Name: 1, dtype: int32
2 num1    3
num2    2
Name: 2, dtype: int32
3 num1    3
num2    4
Name: 3, dtype: int32
4 num1    1
num2    2
Name: 4, dtype: int32
5 num1    9
num2    1
Name: 5, dtype: int32
6 num1    4
num2    6
Name: 6, dtype: int32
7 num1    8
num2    2
Name: 7, dtype: int32
8 num1    3
num2    0
Name: 8, dtype: int32
9 num1    0
num2    6
Name: 9, dtype: int32


### itertuples()

In [75]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), columns=['num1', 'num2'])

for row in df.itertuples():
    print(row)

Pandas(Index=0, num1=2, num2=1)
Pandas(Index=1, num1=4, num2=2)
Pandas(Index=2, num1=5, num2=5)
Pandas(Index=3, num1=5, num2=2)
Pandas(Index=4, num1=5, num2=7)
Pandas(Index=5, num1=7, num2=6)
Pandas(Index=6, num1=1, num2=6)
Pandas(Index=7, num1=7, num2=2)
Pandas(Index=8, num1=3, num2=1)
Pandas(Index=9, num1=9, num2=5)


### index 속성 이용

In [81]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), columns=['num1', 'num2'])

for i in df.index: 
     print(df["num1"][i], df["num2"][i])

6 5
0 0
3 1
9 9
6 6
7 8
8 7
0 8
6 8
9 8


### zip() 
for 문에 여러개 컬럼을 지정하고 싶은 경우

In [77]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), columns=['num1', 'num2'])

for num1, num2 in zip(df['num1'], df['num2']):
    print(num1, num2)

8 7
7 1
8 4
7 0
4 9
0 6
4 2
4 6
3 3
7 8


### One Column

In [79]:
df = pd.DataFrame(np.random.randint(0, 10, size=(10, 2)), columns=['num1', 'num2'])

for num1 in df['num1']:
    print(num1)

5
8
4
4
3
9
5
3
7
7


### loc 메서드 이용

In [82]:
for i in range(len(df)): 
     print(df.loc[i,'num1'], df.loc[i,'num2'])

6 5
0 0
3 1
9 9
6 6
7 8
8 7
0 8
6 8
9 8


### iloc 메서드 이용

In [83]:
for i in range(len(df)): 
     print(df.iloc[i,0], df.iloc[i,1])

6 5
0 0
3 1
9 9
6 6
7 8
8 7
0 8
6 8
9 8


pandas.DataFrame.apply는 DataFrame을 반환합니다. DataFrame의 주어진 축을 따라 주어진 함수를 적용한 결과.

DataFrame.apply(self, 
                func, 
                axis=0, 
                raw=False, 
                result_type=None, 
                args=(), 
                **kwds)
                
여기서 func는 적용 할 함수를 나타내고 axis는 함수가 적용되는 축을 나타냅니다. axis = 1 또는axis = 'columns'를 사용하여 각 행에 함수를 적용 할 수 있습니다.

In [84]:
import pandas as pd

dates=['April-10', 'April-11', 'April-12', 'April-13','April-14','April-16']
income1=[10,20,10,15,10,12]
income2=[20,30,10,5,40,13]

df=pd.DataFrame({"Date":dates,
                "Income_1":income1,
                "Income_2":income2})


        
print(df.apply(lambda row: "Total income in "+ row["Date"]+ " is:"+str(row["Income_1"]+row["Income_2"]),axis=1))

0    Total income in April-10 is:30
1    Total income in April-11 is:50
2    Total income in April-12 is:20
3    Total income in April-13 is:20
4    Total income in April-14 is:50
5    Total income in April-16 is:25
dtype: object


3차원 자료구조인 Panel은 Axis 0 (items), Axis 1 (major_axis), Axis 2 (minor_axis) 등 3개의 축을 가지고 있는데, Axis 0은 그 한 요소가 2차원의 DataFrame 에 해당되며, Axis 1은 DataFrame의 행(row)에 해당되고, Axis 2는 DataFrame의 열(column)에 해당된다. 아래 예제는 numpy를 사용하여 3차원 난수를 발생시킨 후, 이를 pandas.Panel() 에 적용한 예이다. 출력 결과에 보면, 2 (items) x 3 (major_axis) x 4 (minor_axis) 크기의 Panel 객체가 생성되었음을 알 수 있다. Panel 객체 p로부터 p[0]을 조회하면, Axis 0 의 첫번째 요소인 DataFrame이 출력됨을 볼 수 있다.

In [5]:
data = np.random.rand(2,3,4)
p = pd.Panel(data)
# print(p) error 
p[0]

<ipython-input-5-484ab45e6566>:2: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  p = pd.Panel(data)


TypeError: Panel() takes no arguments

In [6]:
df1 = pd.DataFrame({'Name':['Kim', 'Lee', 'Park'], 'Gender':['M', 'M', 'F'], 'Mid':[90, 85, 95]})
df1

Name Gender  Mid
0   Kim      M   90
1   Lee      M   85
2  Park      F   95

In [7]:
df2 = pd.DataFrame({'Name':['Wolfpack', 'Ray'], 'Mid':[90, 95]})
df2

Name  Mid
0  Wolfpack   90
1       Ray   95

In [8]:
df3 = pd.DataFrame({'Name':['Wolfpack', 'Ray'], 'Gender':['M', 'F'], 'Mid':[90, 95]})
df3

Name Gender  Mid
0  Wolfpack      M   90
1       Ray      F   95

In [9]:
df4 = pd.DataFrame({'Name':['Lee', 'Kim', 'Park', 'Wolfpack', 'Ray'], 'PopQuiz':[80, 85, 90, 95, 95]})
df4

Name  PopQuiz
0       Lee       80
1       Kim       85
2      Park       90
3  Wolfpack       95
4       Ray       95

In [10]:
df5 = pd.DataFrame({'Name':['Kim', 'Lee', 'Wolfpack', 'Ray'], 'Final':[90, 85, 95, 95]})
df5

Name  Final
0       Kim     90
1       Lee     85
2  Wolfpack     95
3       Ray     95

## 가로 합치기 df.concat([df1, df2], axis=0, join='outer')
- axis: 행 혹은 열 합치기 1=열 합치기
- join: outer=합치기, inner=교집합

#### 두 데이터프레임이 공통변수가 동일한 경우 pd.concat([df1, df2])
- df1.append(df2)와 동일

#### 두 데이터프레임 변수가 다른 경우 없는것은 결측치

#### 두 데이터프레임이 공통적으로 있는 변수 합치기 join='inner'

In [14]:
pd.concat([df1, df2])

Name Gender  Mid
0       Kim      M   90
1       Lee      M   85
2      Park      F   95
0  Wolfpack    NaN   90
1       Ray    NaN   95

In [15]:
df1.append(df2)

Name Gender  Mid
0       Kim      M   90
1       Lee      M   85
2      Park      F   95
0  Wolfpack    NaN   90
1       Ray    NaN   95

In [17]:
pd.concat([df1, df2], join='inner')

Name  Mid
0       Kim   90
1       Lee   85
2      Park   95
0  Wolfpack   90
1       Ray   95

## 가로 합치기 df.concat([df1, df2], axis=1, join='outer')
두 데이터프레임 세로 병렬합치기
- join = 'outer' (합집합 합치기) - 디폴트: 행 개수가 적은 경우 NaN 결측치
- join = 'inner' (교집합 합치기) - 행 개수가 적은 데이터 프레임 행 개수만 저장

In [18]:
pd.concat([df3, df1], axis=1)

Name Gender   Mid  Name Gender  Mid
0  Wolfpack      M  90.0   Kim      M   90
1       Ray      F  95.0   Lee      M   85
2       NaN    NaN   NaN  Park      F   95

In [19]:
pd.concat([df3, df1], axis=1, join='inner')

Name Gender  Mid Name Gender  Mid
0  Wolfpack      M   90  Kim      M   90
1       Ray      F   95  Lee      M   85

## 세로 합치지 merge - pd.merge(left, right, how='inner', on=None)
- on=[['키변수1', '키변수2']] 데이테프레임 합치는 매칭 키 변수 지정, 없으면 병렬 합치기
- how: inner(교집합), outer(합집합), left(왼쪽 데이터 프레임 키변수 사용), right(오른쪽 데이터 프레임 키변수 사용)

In [20]:
df0=pd.concat([df1, df3])
df0

Name Gender  Mid
0       Kim      M   90
1       Lee      M   85
2      Park      F   95
0  Wolfpack      M   90
1       Ray      F   95

In [21]:
pd.merge(df0, df5, on='Name')

Name Gender  Mid  PopQuiz
0       Kim      M   90       85
1       Lee      M   85       80
2      Park      F   95       90
3  Wolfpack      M   90       95
4       Ray      F   95       95

In [22]:
pd.merge(df0, df5, how='outer', on='Name')

Name Gender  Mid  Final
0       Kim      M   90   90.0
1       Lee      M   85   85.0
2      Park      F   95    NaN
3  Wolfpack      M   90   95.0
4       Ray      F   95   95.0

예제코드 부분 추가
http://wolfpack.hannam.ac.kr/Stat_Notes/softwares/Python/%ED%8C%8C%EC%9D%B4%EC%8D%AC_Pandas%ED%95%A9%EC%B9%98%EA%B8%B0.pdf

## 행(Row) 갯수 
count()는 Null 값이 아닌 행(count Non-null rows)만 세며,  
size() 는 Null 값인 행도 모두 포함해서 행(size of all rows)을 센다

판다스 dataframe과 series 행 갯수 세는 방법
https://rfriend.tistory.com/450